//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ConsoleApplication1.WebReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="GeraGuiaGnreSoapBinding", Namespace="http://guiasgnre/webgnre")]
    public partial class GeraGuiaGnre : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GeraGuiaOperationCompleted;
        
        private System.Threading.SendOrPostCallback GeraGuiaPDFOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscaGuiasPendentesOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscaTodasGuiasPendentesOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscaTodasGuiasComErroOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscaGuiaOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscaGuiaPDFOperationCompleted;
        
        private System.Threading.SendOrPostCallback Assinatura_gratisOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public GeraGuiaGnre() {
            this.Url = global::ConsoleApplication1.Properties.Settings.Default.ConsoleApplication1_WebReference_GeraGuiaGnre;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GeraGuiaCompletedEventHandler GeraGuiaCompleted;
        
        /// <remarks/>
        public event GeraGuiaPDFCompletedEventHandler GeraGuiaPDFCompleted;
        
        /// <remarks/>
        public event BuscaGuiasPendentesCompletedEventHandler BuscaGuiasPendentesCompleted;
        
        /// <remarks/>
        public event BuscaTodasGuiasPendentesCompletedEventHandler BuscaTodasGuiasPendentesCompleted;
        
        /// <remarks/>
        public event BuscaTodasGuiasComErroCompletedEventHandler BuscaTodasGuiasComErroCompleted;
        
        /// <remarks/>
        public event BuscaGuiaCompletedEventHandler BuscaGuiaCompleted;
        
        /// <remarks/>
        public event BuscaGuiaPDFCompletedEventHandler BuscaGuiaPDFCompleted;
        
        /// <remarks/>
        public event Assinatura_gratisCompletedEventHandler Assinatura_gratisCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://guiasgnre/webgnre", ResponseNamespace="http://guiasgnre/webgnre", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public tRetornoLote GeraGuia(string sEmpresa, string sUsuario, string sChaveApi, tListaNfe ListaNfe) {
            object[] results = this.Invoke("GeraGuia", new object[] {
                        sEmpresa,
                        sUsuario,
                        sChaveApi,
                        ListaNfe});
            return ((tRetornoLote)(results[0]));
        }
        
        /// <remarks/>
        public void GeraGuiaAsync(string sEmpresa, string sUsuario, string sChaveApi, tListaNfe ListaNfe) {
            this.GeraGuiaAsync(sEmpresa, sUsuario, sChaveApi, ListaNfe, null);
        }
        
        /// <remarks/>
        public void GeraGuiaAsync(string sEmpresa, string sUsuario, string sChaveApi, tListaNfe ListaNfe, object userState) {
            if ((this.GeraGuiaOperationCompleted == null)) {
                this.GeraGuiaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGeraGuiaOperationCompleted);
            }
            this.InvokeAsync("GeraGuia", new object[] {
                        sEmpresa,
                        sUsuario,
                        sChaveApi,
                        ListaNfe}, this.GeraGuiaOperationCompleted, userState);
        }
        
        private void OnGeraGuiaOperationCompleted(object arg) {
            if ((this.GeraGuiaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GeraGuiaCompleted(this, new GeraGuiaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://guiasgnre/webgnre", ResponseNamespace="http://guiasgnre/webgnre", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public tRetornoLotePDF GeraGuiaPDF(string sEmpresa, string sUsuario, string sChaveApi, tListaNfe ListaNfe) {
            object[] results = this.Invoke("GeraGuiaPDF", new object[] {
                        sEmpresa,
                        sUsuario,
                        sChaveApi,
                        ListaNfe});
            return ((tRetornoLotePDF)(results[0]));
        }
        
        /// <remarks/>
        public void GeraGuiaPDFAsync(string sEmpresa, string sUsuario, string sChaveApi, tListaNfe ListaNfe) {
            this.GeraGuiaPDFAsync(sEmpresa, sUsuario, sChaveApi, ListaNfe, null);
        }
        
        /// <remarks/>
        public void GeraGuiaPDFAsync(string sEmpresa, string sUsuario, string sChaveApi, tListaNfe ListaNfe, object userState) {
            if ((this.GeraGuiaPDFOperationCompleted == null)) {
                this.GeraGuiaPDFOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGeraGuiaPDFOperationCompleted);
            }
            this.InvokeAsync("GeraGuiaPDF", new object[] {
                        sEmpresa,
                        sUsuario,
                        sChaveApi,
                        ListaNfe}, this.GeraGuiaPDFOperationCompleted, userState);
        }
        
        private void OnGeraGuiaPDFOperationCompleted(object arg) {
            if ((this.GeraGuiaPDFCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GeraGuiaPDFCompleted(this, new GeraGuiaPDFCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://guiasgnre/webgnre", ResponseNamespace="http://guiasgnre/webgnre", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public tListaGuias BuscaGuiasPendentes(string sEmpresa, string sUsuario, string sChaveApi, tRecibos GuiasPendentes) {
            object[] results = this.Invoke("BuscaGuiasPendentes", new object[] {
                        sEmpresa,
                        sUsuario,
                        sChaveApi,
                        GuiasPendentes});
            return ((tListaGuias)(results[0]));
        }
        
        /// <remarks/>
        public void BuscaGuiasPendentesAsync(string sEmpresa, string sUsuario, string sChaveApi, tRecibos GuiasPendentes) {
            this.BuscaGuiasPendentesAsync(sEmpresa, sUsuario, sChaveApi, GuiasPendentes, null);
        }
        
        /// <remarks/>
        public void BuscaGuiasPendentesAsync(string sEmpresa, string sUsuario, string sChaveApi, tRecibos GuiasPendentes, object userState) {
            if ((this.BuscaGuiasPendentesOperationCompleted == null)) {
                this.BuscaGuiasPendentesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscaGuiasPendentesOperationCompleted);
            }
            this.InvokeAsync("BuscaGuiasPendentes", new object[] {
                        sEmpresa,
                        sUsuario,
                        sChaveApi,
                        GuiasPendentes}, this.BuscaGuiasPendentesOperationCompleted, userState);
        }
        
        private void OnBuscaGuiasPendentesOperationCompleted(object arg) {
            if ((this.BuscaGuiasPendentesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscaGuiasPendentesCompleted(this, new BuscaGuiasPendentesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://guiasgnre/webgnre", ResponseNamespace="http://guiasgnre/webgnre", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public tListaGuias BuscaTodasGuiasPendentes(string sEmpresa, string sUsuario, string sChaveApi, string sDataInicio, string sDataFim) {
            object[] results = this.Invoke("BuscaTodasGuiasPendentes", new object[] {
                        sEmpresa,
                        sUsuario,
                        sChaveApi,
                        sDataInicio,
                        sDataFim});
            return ((tListaGuias)(results[0]));
        }
        
        /// <remarks/>
        public void BuscaTodasGuiasPendentesAsync(string sEmpresa, string sUsuario, string sChaveApi, string sDataInicio, string sDataFim) {
            this.BuscaTodasGuiasPendentesAsync(sEmpresa, sUsuario, sChaveApi, sDataInicio, sDataFim, null);
        }
        
        /// <remarks/>
        public void BuscaTodasGuiasPendentesAsync(string sEmpresa, string sUsuario, string sChaveApi, string sDataInicio, string sDataFim, object userState) {
            if ((this.BuscaTodasGuiasPendentesOperationCompleted == null)) {
                this.BuscaTodasGuiasPendentesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscaTodasGuiasPendentesOperationCompleted);
            }
            this.InvokeAsync("BuscaTodasGuiasPendentes", new object[] {
                        sEmpresa,
                        sUsuario,
                        sChaveApi,
                        sDataInicio,
                        sDataFim}, this.BuscaTodasGuiasPendentesOperationCompleted, userState);
        }
        
        private void OnBuscaTodasGuiasPendentesOperationCompleted(object arg) {
            if ((this.BuscaTodasGuiasPendentesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscaTodasGuiasPendentesCompleted(this, new BuscaTodasGuiasPendentesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://guiasgnre/webgnre", ResponseNamespace="http://guiasgnre/webgnre", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public tListaGuias BuscaTodasGuiasComErro(string sEmpresa, string sUsuario, string sChaveApi, string sDataInicio, string sDataFim) {
            object[] results = this.Invoke("BuscaTodasGuiasComErro", new object[] {
                        sEmpresa,
                        sUsuario,
                        sChaveApi,
                        sDataInicio,
                        sDataFim});
            return ((tListaGuias)(results[0]));
        }
        
        /// <remarks/>
        public void BuscaTodasGuiasComErroAsync(string sEmpresa, string sUsuario, string sChaveApi, string sDataInicio, string sDataFim) {
            this.BuscaTodasGuiasComErroAsync(sEmpresa, sUsuario, sChaveApi, sDataInicio, sDataFim, null);
        }
        
        /// <remarks/>
        public void BuscaTodasGuiasComErroAsync(string sEmpresa, string sUsuario, string sChaveApi, string sDataInicio, string sDataFim, object userState) {
            if ((this.BuscaTodasGuiasComErroOperationCompleted == null)) {
                this.BuscaTodasGuiasComErroOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscaTodasGuiasComErroOperationCompleted);
            }
            this.InvokeAsync("BuscaTodasGuiasComErro", new object[] {
                        sEmpresa,
                        sUsuario,
                        sChaveApi,
                        sDataInicio,
                        sDataFim}, this.BuscaTodasGuiasComErroOperationCompleted, userState);
        }
        
        private void OnBuscaTodasGuiasComErroOperationCompleted(object arg) {
            if ((this.BuscaTodasGuiasComErroCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscaTodasGuiasComErroCompleted(this, new BuscaTodasGuiasComErroCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://guiasgnre/webgnre", ResponseNamespace="http://guiasgnre/webgnre", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public tListaGuias BuscaGuia(string sEmpresa, string sUsuario, string sChaveApi, tRetornoLote Lote) {
            object[] results = this.Invoke("BuscaGuia", new object[] {
                        sEmpresa,
                        sUsuario,
                        sChaveApi,
                        Lote});
            return ((tListaGuias)(results[0]));
        }
        
        /// <remarks/>
        public void BuscaGuiaAsync(string sEmpresa, string sUsuario, string sChaveApi, tRetornoLote Lote) {
            this.BuscaGuiaAsync(sEmpresa, sUsuario, sChaveApi, Lote, null);
        }
        
        /// <remarks/>
        public void BuscaGuiaAsync(string sEmpresa, string sUsuario, string sChaveApi, tRetornoLote Lote, object userState) {
            if ((this.BuscaGuiaOperationCompleted == null)) {
                this.BuscaGuiaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscaGuiaOperationCompleted);
            }
            this.InvokeAsync("BuscaGuia", new object[] {
                        sEmpresa,
                        sUsuario,
                        sChaveApi,
                        Lote}, this.BuscaGuiaOperationCompleted, userState);
        }
        
        private void OnBuscaGuiaOperationCompleted(object arg) {
            if ((this.BuscaGuiaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscaGuiaCompleted(this, new BuscaGuiaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://guiasgnre/webgnre", ResponseNamespace="http://guiasgnre/webgnre", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public tRetornoLotePDF BuscaGuiaPDF(string sEmpresa, string sUsuario, string sChaveApi, tRetornoLote Lote) {
            object[] results = this.Invoke("BuscaGuiaPDF", new object[] {
                        sEmpresa,
                        sUsuario,
                        sChaveApi,
                        Lote});
            return ((tRetornoLotePDF)(results[0]));
        }
        
        /// <remarks/>
        public void BuscaGuiaPDFAsync(string sEmpresa, string sUsuario, string sChaveApi, tRetornoLote Lote) {
            this.BuscaGuiaPDFAsync(sEmpresa, sUsuario, sChaveApi, Lote, null);
        }
        
        /// <remarks/>
        public void BuscaGuiaPDFAsync(string sEmpresa, string sUsuario, string sChaveApi, tRetornoLote Lote, object userState) {
            if ((this.BuscaGuiaPDFOperationCompleted == null)) {
                this.BuscaGuiaPDFOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscaGuiaPDFOperationCompleted);
            }
            this.InvokeAsync("BuscaGuiaPDF", new object[] {
                        sEmpresa,
                        sUsuario,
                        sChaveApi,
                        Lote}, this.BuscaGuiaPDFOperationCompleted, userState);
        }
        
        private void OnBuscaGuiaPDFOperationCompleted(object arg) {
            if ((this.BuscaGuiaPDFCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscaGuiaPDFCompleted(this, new BuscaGuiaPDFCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://guiasgnre/webgnre", ResponseNamespace="http://guiasgnre/webgnre", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public tRetornoAssinatura Assinatura_gratis(tAssinatura Assinatura) {
            object[] results = this.Invoke("Assinatura_gratis", new object[] {
                        Assinatura});
            return ((tRetornoAssinatura)(results[0]));
        }
        
        /// <remarks/>
        public void Assinatura_gratisAsync(tAssinatura Assinatura) {
            this.Assinatura_gratisAsync(Assinatura, null);
        }
        
        /// <remarks/>
        public void Assinatura_gratisAsync(tAssinatura Assinatura, object userState) {
            if ((this.Assinatura_gratisOperationCompleted == null)) {
                this.Assinatura_gratisOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAssinatura_gratisOperationCompleted);
            }
            this.InvokeAsync("Assinatura_gratis", new object[] {
                        Assinatura}, this.Assinatura_gratisOperationCompleted, userState);
        }
        
        private void OnAssinatura_gratisOperationCompleted(object arg) {
            if ((this.Assinatura_gratisCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Assinatura_gratisCompleted(this, new Assinatura_gratisCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://guiasgnre/webgnre")]
    public partial class tListaNfe {
        
        private tDadosNfe[] itensField;
        
        /// <remarks/>
        public tDadosNfe[] itens {
            get {
                return this.itensField;
            }
            set {
                this.itensField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://guiasgnre/webgnre")]
    public partial class tDadosNfe {
        
        private string emitenteField;
        
        private string serieField;
        
        private string modeloField;
        
        private decimal num_nota_fiscalField;
        
        private string tipo_documentoField;
        
        private string chave_nfeField;
        
        private string convenioField;
        
        private string data_emissaoField;
        
        private string produtoField;
        
        private string vencimentoField;
        
        private decimal valorField;
        
        private decimal icms_uf_destinoField;
        
        private decimal fcp_uf_destinoField;
        
        private string cpfField;
        
        private string cnpjField;
        
        private string nome_destinatarioField;
        
        private string municipio_destinatarioField;
        
        private string cod_municipio_destinatField;
        
        private string uf_destinatarioField;
        
        private string data_recepcaoField;
        
        private decimal icms_stField;
        
        /// <remarks/>
        public string emitente {
            get {
                return this.emitenteField;
            }
            set {
                this.emitenteField = value;
            }
        }
        
        /// <remarks/>
        public string serie {
            get {
                return this.serieField;
            }
            set {
                this.serieField = value;
            }
        }
        
        /// <remarks/>
        public string modelo {
            get {
                return this.modeloField;
            }
            set {
                this.modeloField = value;
            }
        }
        
        /// <remarks/>
        public decimal num_nota_fiscal {
            get {
                return this.num_nota_fiscalField;
            }
            set {
                this.num_nota_fiscalField = value;
            }
        }
        
        /// <remarks/>
        public string tipo_documento {
            get {
                return this.tipo_documentoField;
            }
            set {
                this.tipo_documentoField = value;
            }
        }
        
        /// <remarks/>
        public string chave_nfe {
            get {
                return this.chave_nfeField;
            }
            set {
                this.chave_nfeField = value;
            }
        }
        
        /// <remarks/>
        public string convenio {
            get {
                return this.convenioField;
            }
            set {
                this.convenioField = value;
            }
        }
        
        /// <remarks/>
        public string data_emissao {
            get {
                return this.data_emissaoField;
            }
            set {
                this.data_emissaoField = value;
            }
        }
        
        /// <remarks/>
        public string produto {
            get {
                return this.produtoField;
            }
            set {
                this.produtoField = value;
            }
        }
        
        /// <remarks/>
        public string vencimento {
            get {
                return this.vencimentoField;
            }
            set {
                this.vencimentoField = value;
            }
        }
        
        /// <remarks/>
        public decimal valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
            }
        }
        
        /// <remarks/>
        public decimal icms_uf_destino {
            get {
                return this.icms_uf_destinoField;
            }
            set {
                this.icms_uf_destinoField = value;
            }
        }
        
        /// <remarks/>
        public decimal fcp_uf_destino {
            get {
                return this.fcp_uf_destinoField;
            }
            set {
                this.fcp_uf_destinoField = value;
            }
        }
        
        /// <remarks/>
        public string cpf {
            get {
                return this.cpfField;
            }
            set {
                this.cpfField = value;
            }
        }
        
        /// <remarks/>
        public string cnpj {
            get {
                return this.cnpjField;
            }
            set {
                this.cnpjField = value;
            }
        }
        
        /// <remarks/>
        public string nome_destinatario {
            get {
                return this.nome_destinatarioField;
            }
            set {
                this.nome_destinatarioField = value;
            }
        }
        
        /// <remarks/>
        public string municipio_destinatario {
            get {
                return this.municipio_destinatarioField;
            }
            set {
                this.municipio_destinatarioField = value;
            }
        }
        
        /// <remarks/>
        public string cod_municipio_destinat {
            get {
                return this.cod_municipio_destinatField;
            }
            set {
                this.cod_municipio_destinatField = value;
            }
        }
        
        /// <remarks/>
        public string uf_destinatario {
            get {
                return this.uf_destinatarioField;
            }
            set {
                this.uf_destinatarioField = value;
            }
        }
        
        /// <remarks/>
        public string data_recepcao {
            get {
                return this.data_recepcaoField;
            }
            set {
                this.data_recepcaoField = value;
            }
        }
        
        /// <remarks/>
        public decimal icms_st {
            get {
                return this.icms_stField;
            }
            set {
                this.icms_stField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://guiasgnre/webgnre")]
    public partial class tRetornoAssinatura {
        
        private string loginField;
        
        private string razaoField;
        
        private string cNPJField;
        
        private string tokenAPIField;
        
        private int retornoField;
        
        private string msg_retornoField;
        
        /// <remarks/>
        public string Login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
            }
        }
        
        /// <remarks/>
        public string Razao {
            get {
                return this.razaoField;
            }
            set {
                this.razaoField = value;
            }
        }
        
        /// <remarks/>
        public string CNPJ {
            get {
                return this.cNPJField;
            }
            set {
                this.cNPJField = value;
            }
        }
        
        /// <remarks/>
        public string TokenAPI {
            get {
                return this.tokenAPIField;
            }
            set {
                this.tokenAPIField = value;
            }
        }
        
        /// <remarks/>
        public int Retorno {
            get {
                return this.retornoField;
            }
            set {
                this.retornoField = value;
            }
        }
        
        /// <remarks/>
        public string Msg_retorno {
            get {
                return this.msg_retornoField;
            }
            set {
                this.msg_retornoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://guiasgnre/webgnre")]
    public partial class tAssinatura {
        
        private string nomeField;
        
        private string loginField;
        
        private string senhaField;
        
        private string razaoField;
        
        private string fantasiaField;
        
        private string telefoneField;
        
        private string cepField;
        
        private string logradouroField;
        
        private string nroField;
        
        private string complementoField;
        
        private string bairroField;
        
        private string codigo_cidadeField;
        
        private string codigo_ufField;
        
        private string cNPJField;
        
        /// <remarks/>
        public string Nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
        
        /// <remarks/>
        public string Login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
            }
        }
        
        /// <remarks/>
        public string Senha {
            get {
                return this.senhaField;
            }
            set {
                this.senhaField = value;
            }
        }
        
        /// <remarks/>
        public string Razao {
            get {
                return this.razaoField;
            }
            set {
                this.razaoField = value;
            }
        }
        
        /// <remarks/>
        public string Fantasia {
            get {
                return this.fantasiaField;
            }
            set {
                this.fantasiaField = value;
            }
        }
        
        /// <remarks/>
        public string Telefone {
            get {
                return this.telefoneField;
            }
            set {
                this.telefoneField = value;
            }
        }
        
        /// <remarks/>
        public string Cep {
            get {
                return this.cepField;
            }
            set {
                this.cepField = value;
            }
        }
        
        /// <remarks/>
        public string Logradouro {
            get {
                return this.logradouroField;
            }
            set {
                this.logradouroField = value;
            }
        }
        
        /// <remarks/>
        public string Nro {
            get {
                return this.nroField;
            }
            set {
                this.nroField = value;
            }
        }
        
        /// <remarks/>
        public string Complemento {
            get {
                return this.complementoField;
            }
            set {
                this.complementoField = value;
            }
        }
        
        /// <remarks/>
        public string Bairro {
            get {
                return this.bairroField;
            }
            set {
                this.bairroField = value;
            }
        }
        
        /// <remarks/>
        public string Codigo_cidade {
            get {
                return this.codigo_cidadeField;
            }
            set {
                this.codigo_cidadeField = value;
            }
        }
        
        /// <remarks/>
        public string Codigo_uf {
            get {
                return this.codigo_ufField;
            }
            set {
                this.codigo_ufField = value;
            }
        }
        
        /// <remarks/>
        public string CNPJ {
            get {
                return this.cNPJField;
            }
            set {
                this.cNPJField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://guiasgnre/webgnre")]
    public partial class tGuias {
        
        private string emitenteField;
        
        private string serieField;
        
        private string modeloField;
        
        private decimal num_nota_fiscalField;
        
        private string receitaField;
        
        private string detalhamentoField;
        
        private string tipo_documentoField;
        
        private string chave_nfeField;
        
        private string convenioField;
        
        private string data_emissaoField;
        
        private string statusField;
        
        private string reciboField;
        
        private string data_reciboField;
        
        private string produtoField;
        
        private string vencimentoField;
        
        private decimal valorField;
        
        private string cpfField;
        
        private string cnpjField;
        
        private string nome_destinatarioField;
        
        private string municipio_destinatarioField;
        
        private string cod_municipio_destinatField;
        
        private string uf_destinatarioField;
        
        private string mensagemField;
        
        private string xml_guiaField;
        
        private string data_recepcaoField;
        
        private decimal valor_atualizadoField;
        
        /// <remarks/>
        public string emitente {
            get {
                return this.emitenteField;
            }
            set {
                this.emitenteField = value;
            }
        }
        
        /// <remarks/>
        public string serie {
            get {
                return this.serieField;
            }
            set {
                this.serieField = value;
            }
        }
        
        /// <remarks/>
        public string modelo {
            get {
                return this.modeloField;
            }
            set {
                this.modeloField = value;
            }
        }
        
        /// <remarks/>
        public decimal num_nota_fiscal {
            get {
                return this.num_nota_fiscalField;
            }
            set {
                this.num_nota_fiscalField = value;
            }
        }
        
        /// <remarks/>
        public string receita {
            get {
                return this.receitaField;
            }
            set {
                this.receitaField = value;
            }
        }
        
        /// <remarks/>
        public string detalhamento {
            get {
                return this.detalhamentoField;
            }
            set {
                this.detalhamentoField = value;
            }
        }
        
        /// <remarks/>
        public string tipo_documento {
            get {
                return this.tipo_documentoField;
            }
            set {
                this.tipo_documentoField = value;
            }
        }
        
        /// <remarks/>
        public string chave_nfe {
            get {
                return this.chave_nfeField;
            }
            set {
                this.chave_nfeField = value;
            }
        }
        
        /// <remarks/>
        public string convenio {
            get {
                return this.convenioField;
            }
            set {
                this.convenioField = value;
            }
        }
        
        /// <remarks/>
        public string data_emissao {
            get {
                return this.data_emissaoField;
            }
            set {
                this.data_emissaoField = value;
            }
        }
        
        /// <remarks/>
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string recibo {
            get {
                return this.reciboField;
            }
            set {
                this.reciboField = value;
            }
        }
        
        /// <remarks/>
        public string data_recibo {
            get {
                return this.data_reciboField;
            }
            set {
                this.data_reciboField = value;
            }
        }
        
        /// <remarks/>
        public string produto {
            get {
                return this.produtoField;
            }
            set {
                this.produtoField = value;
            }
        }
        
        /// <remarks/>
        public string vencimento {
            get {
                return this.vencimentoField;
            }
            set {
                this.vencimentoField = value;
            }
        }
        
        /// <remarks/>
        public decimal valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
            }
        }
        
        /// <remarks/>
        public string cpf {
            get {
                return this.cpfField;
            }
            set {
                this.cpfField = value;
            }
        }
        
        /// <remarks/>
        public string cnpj {
            get {
                return this.cnpjField;
            }
            set {
                this.cnpjField = value;
            }
        }
        
        /// <remarks/>
        public string nome_destinatario {
            get {
                return this.nome_destinatarioField;
            }
            set {
                this.nome_destinatarioField = value;
            }
        }
        
        /// <remarks/>
        public string municipio_destinatario {
            get {
                return this.municipio_destinatarioField;
            }
            set {
                this.municipio_destinatarioField = value;
            }
        }
        
        /// <remarks/>
        public string cod_municipio_destinat {
            get {
                return this.cod_municipio_destinatField;
            }
            set {
                this.cod_municipio_destinatField = value;
            }
        }
        
        /// <remarks/>
        public string uf_destinatario {
            get {
                return this.uf_destinatarioField;
            }
            set {
                this.uf_destinatarioField = value;
            }
        }
        
        /// <remarks/>
        public string mensagem {
            get {
                return this.mensagemField;
            }
            set {
                this.mensagemField = value;
            }
        }
        
        /// <remarks/>
        public string xml_guia {
            get {
                return this.xml_guiaField;
            }
            set {
                this.xml_guiaField = value;
            }
        }
        
        /// <remarks/>
        public string data_recepcao {
            get {
                return this.data_recepcaoField;
            }
            set {
                this.data_recepcaoField = value;
            }
        }
        
        /// <remarks/>
        public decimal valor_atualizado {
            get {
                return this.valor_atualizadoField;
            }
            set {
                this.valor_atualizadoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://guiasgnre/webgnre")]
    public partial class tListaGuias {
        
        private tGuias[] guiasField;
        
        private int retornoField;
        
        private string msg_retornoField;
        
        /// <remarks/>
        public tGuias[] guias {
            get {
                return this.guiasField;
            }
            set {
                this.guiasField = value;
            }
        }
        
        /// <remarks/>
        public int retorno {
            get {
                return this.retornoField;
            }
            set {
                this.retornoField = value;
            }
        }
        
        /// <remarks/>
        public string msg_retorno {
            get {
                return this.msg_retornoField;
            }
            set {
                this.msg_retornoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://guiasgnre/webgnre")]
    public partial class tRecibos {
        
        private string emitenteField;
        
        private string[] reciboField;
        
        /// <remarks/>
        public string emitente {
            get {
                return this.emitenteField;
            }
            set {
                this.emitenteField = value;
            }
        }
        
        /// <remarks/>
        public string[] recibo {
            get {
                return this.reciboField;
            }
            set {
                this.reciboField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://guiasgnre/webgnre")]
    public partial class tPdfGuias {
        
        private System.Nullable<byte>[] pdfField;
        
        private string nomeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute()]
        [System.Xml.Serialization.XmlArrayItemAttribute()]
        public System.Nullable<byte>[] pdf {
            get {
                return this.pdfField;
            }
            set {
                this.pdfField = value;
            }
        }
        
        /// <remarks/>
        public string nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://guiasgnre/webgnre")]
    public partial class tRetornoLotePDF {
        
        private int retornoField;
        
        private string msg_retornoField;
        
        private int loteField;
        
        private tPdfGuias[] pdf_guiasField;
        
        /// <remarks/>
        public int retorno {
            get {
                return this.retornoField;
            }
            set {
                this.retornoField = value;
            }
        }
        
        /// <remarks/>
        public string msg_retorno {
            get {
                return this.msg_retornoField;
            }
            set {
                this.msg_retornoField = value;
            }
        }
        
        /// <remarks/>
        public int lote {
            get {
                return this.loteField;
            }
            set {
                this.loteField = value;
            }
        }
        
        /// <remarks/>
        public tPdfGuias[] pdf_guias {
            get {
                return this.pdf_guiasField;
            }
            set {
                this.pdf_guiasField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://guiasgnre/webgnre")]
    public partial class tReciboNota {
        
        private string emitenteField;
        
        private int num_nota_fiscalField;
        
        private string modeloField;
        
        private string serieField;
        
        private string emissao_nfField;
        
        private string receitaField;
        
        private string statusField;
        
        private string reciboField;
        
        private string data_reciboField;
        
        /// <remarks/>
        public string emitente {
            get {
                return this.emitenteField;
            }
            set {
                this.emitenteField = value;
            }
        }
        
        /// <remarks/>
        public int num_nota_fiscal {
            get {
                return this.num_nota_fiscalField;
            }
            set {
                this.num_nota_fiscalField = value;
            }
        }
        
        /// <remarks/>
        public string modelo {
            get {
                return this.modeloField;
            }
            set {
                this.modeloField = value;
            }
        }
        
        /// <remarks/>
        public string serie {
            get {
                return this.serieField;
            }
            set {
                this.serieField = value;
            }
        }
        
        /// <remarks/>
        public string emissao_nf {
            get {
                return this.emissao_nfField;
            }
            set {
                this.emissao_nfField = value;
            }
        }
        
        /// <remarks/>
        public string receita {
            get {
                return this.receitaField;
            }
            set {
                this.receitaField = value;
            }
        }
        
        /// <remarks/>
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string recibo {
            get {
                return this.reciboField;
            }
            set {
                this.reciboField = value;
            }
        }
        
        /// <remarks/>
        public string data_recibo {
            get {
                return this.data_reciboField;
            }
            set {
                this.data_reciboField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1064.2")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://guiasgnre/webgnre")]
    public partial class tRetornoLote {
        
        private int retornoField;
        
        private string msg_retornoField;
        
        private int loteField;
        
        private tReciboNota[] recibosField;
        
        /// <remarks/>
        public int retorno {
            get {
                return this.retornoField;
            }
            set {
                this.retornoField = value;
            }
        }
        
        /// <remarks/>
        public string msg_retorno {
            get {
                return this.msg_retornoField;
            }
            set {
                this.msg_retornoField = value;
            }
        }
        
        /// <remarks/>
        public int lote {
            get {
                return this.loteField;
            }
            set {
                this.loteField = value;
            }
        }
        
        /// <remarks/>
        public tReciboNota[] recibos {
            get {
                return this.recibosField;
            }
            set {
                this.recibosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GeraGuiaCompletedEventHandler(object sender, GeraGuiaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GeraGuiaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GeraGuiaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public tRetornoLote Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((tRetornoLote)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void GeraGuiaPDFCompletedEventHandler(object sender, GeraGuiaPDFCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GeraGuiaPDFCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GeraGuiaPDFCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public tRetornoLotePDF Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((tRetornoLotePDF)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void BuscaGuiasPendentesCompletedEventHandler(object sender, BuscaGuiasPendentesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscaGuiasPendentesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscaGuiasPendentesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public tListaGuias Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((tListaGuias)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void BuscaTodasGuiasPendentesCompletedEventHandler(object sender, BuscaTodasGuiasPendentesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscaTodasGuiasPendentesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscaTodasGuiasPendentesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public tListaGuias Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((tListaGuias)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void BuscaTodasGuiasComErroCompletedEventHandler(object sender, BuscaTodasGuiasComErroCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscaTodasGuiasComErroCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscaTodasGuiasComErroCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public tListaGuias Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((tListaGuias)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void BuscaGuiaCompletedEventHandler(object sender, BuscaGuiaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscaGuiaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscaGuiaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public tListaGuias Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((tListaGuias)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void BuscaGuiaPDFCompletedEventHandler(object sender, BuscaGuiaPDFCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscaGuiaPDFCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscaGuiaPDFCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public tRetornoLotePDF Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((tRetornoLotePDF)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    public delegate void Assinatura_gratisCompletedEventHandler(object sender, Assinatura_gratisCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1038.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Assinatura_gratisCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Assinatura_gratisCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public tRetornoAssinatura Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((tRetornoAssinatura)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591